### PR TITLE
sklnau8825adi audio hardening

### PR DESCRIPTION
**Pull request by bcarnes**
reset more of the card state during initial install
add caroline symlinks to silence confusing alsaucm warning "errors"
Fix comment in skl*max.conf to indicate it is for Sentry

### CODE REVIEW

**Comment by MrChromebox** [comment]
I'd strongly prefer if these commits/PRs referenced either the codec or Skylake audio in general, rather than a single device, just for traceability 

edit: esp since there are Sentry boards with both codecs, commits referencing sentry vs the maxim codec/amp are ambiguous without inspection

**Comment by bcarnes** [comment]
@MrChromebox sure.  Both open PRs and unmerged commits now refer to sklnau8825adi...

**Review by MrChromebox — COMMENTED** [review]
are the symlinks really necessary? are we going to do them for all ~8 Skylake devices?

in sklnau8825max.conf, maybe 'sklnau8825max' instead of 'Sentry'? (and same for sklnau8825adi.conf)

**Comment by MrChromebox** [comment]
@bcarnes thx :)

**Comment by bcarnes** [comment]
@MrChromebox 
> are the symlinks really necessary? are we going to do them for all ~8 Skylake devices?

They are not "necessary", but alsaucm spews warnings prefixed by "Error" before falling back to reading /usr/share/alsa/ucm/sklnau8825adi/sklnau8825adi.conf and actually doing the requested action.

These errors-warnings are not visible when doing everything through the GUI, but are on the console when a human actually tried to run an alsaucm command. 

Comment threads here for GaOS and elsewhere are filled with people thinking they have a broken setup and that the command did nothing, when it actually completes successfully after silently falling back to use the .../ucm/skl*/skl*.conf file.

For example:

With all files missing, an actual error log showing what it looks for in which order, and it giving up and doing nothing with an error:

```
$ alsaucm -c sklnau8825adi reset
ALSA lib utils.c:67:(uc_mgr_config_load) could not open configuration file /usr/share/alsa/ucm/Google-Caroline-1.0-Caroline/Google-Caroline-1.0-Caroline.conf
ALSA lib parser.c:1419:(load_master_config) error: could not parse configuration for card Google-Caroline-1.0-Caroline
ALSA lib utils.c:67:(uc_mgr_config_load) could not open configuration file /usr/share/alsa/ucm/sklnau8825adi/sklnau8825adi.conf
ALSA lib parser.c:1419:(load_master_config) error: could not parse configuration for card sklnau8825adi
ALSA lib main.c:946:(snd_use_case_mgr_open) error: failed to import sklnau8825adi use case configuration -2
alsaucm: error failed to open sound card sklnau8825adi: No such file or directory
$ echo $?
1

```

With just the skl*/skl*.conf files present, a user sees the following (even though it does the action and gives a success exit code):

```
$ alsaucm -c sklnau8825adi reset
ALSA lib utils.c:67:(uc_mgr_config_load) could not open configuration file /usr/share/alsa/ucm/Google-Caroline-1.0-Caroline/Google-Caroline-1.0-Caroline.conf
ALSA lib parser.c:1419:(load_master_config) error: could not parse configuration for card Google-Caroline-1.0-Caroline
$ echo $?
0
```

And with the symlinks, you get no error-warnings, and a success exit code...

I'd say keep the symlinks, to avoid user confusion.  Folks don't think to look at the exit code after seeing those errors.

**Comment by MrChromebox** [comment]
> I'd say keep the symlinks, to avoid user confusion. Folks don't think to look at the exit code after seeing those errors.

but they aren't going to be running anything manually or looking at the log. And we'd need to do it for every device, not just Caroline. And it gets messy with Sentry because it could be either codec.

**Comment by bcarnes** [comment]
@MrChromebox here ya go

**Review by MrChromebox — COMMENTED** [review]
would really prefer not to have model names in the conf files. Sentry could be either. There's more than just Chell/Caroline for the ADI codec (and more than Sentry for the Maxim one)

**Comment by bcarnes** [comment]
@MrChromebox My knee-jerk reaction: just add more model names to the human readable Comment strings...

My thoughts behind that:

I think you're losing something by removing any way for humans to figure out which Chromebook Skylake models correspond to the various codecs.  

As it stands right now, where would a motivated developer figure out which Chromebook models correspond to: sklnau8825max or sklnau8825adi or other codecs?

And where could a motivated developer figure out how which codecs are in Sentry, and if any other models shipped with multiple codecs?

If that existed elsewhere, an alsa "Comment" or a code "# ..." comment inside these codec .conf files pointing to that reference would be sufficient.

If it doesn't exist elsewhere, the info in gallium-skylake:/usr/share/alsa/ucm/X/X.conf, and visible via "alsaucm listcards" becomes that reference.

If you really need to remove this useful information from here, put it somewhere else in the gallium-skylake package as a README that'd be discoverable for someone who stumbles across the sklnau8825{adi,max} files...

**Comment by MrChromebox** [comment]
my point was against having incomplete or inaccurate information, eg listing the nau8825max as for Sentry when it could have either codec, and 4 other devices use it as well

**Comment by bcarnes** [comment]
> 4 other devices use it as well

Exactly... Which 4? :)

Where is that discoverable?

If you haven't written it down anywhere else, write it down here, and I'll add it to these .conf files.

If it is written down somewhere else, I'll nuke the model names from here and put an xref to that documentation.

**Comment by MrChromebox** [comment]
firmware code?

https://github.com/coreboot/coreboot/blob/master/src/mainboard/google/glados/Kconfig.name

**Comment by bcarnes** [comment]
@MrChromebox Perfect, Thanks!  This will be a big boon to other folks trying to help out with audio issues - who don't also live in the coreboot firmware code.

**Pull request merged**
