### PR TITLE
Add support for sklnau8825max

### PR DESCRIPTION
**Pull request by doozan**
This adds the binary firmware needed for sklnau8825max and sets up the appropriate link on installation

The firmware was compiled from the config posted at https://github.com/GalliumOS/galliumos-distro/issues/274#issuecomment-292821069 using the following commands:

wget https://us-east.manta.joyent.com/jmc/public/tmp/sentry.conf -O sklnau8825max.conf
alsatplg -c sklnau8825max.conf -o /lib/firmware/dfw_sst.bin.sklnau8825max

### CODE REVIEW

**Comment by MrChromebox** [comment]
without digging thru those comments, where did the topology .conf file come from?

**Comment by doozan** [comment]
@jclulow posted the link to https://us-east.manta.joyent.com/jmc/public/tmp/0000_SENTRY_dfw_sst.bin and I found the config in the same directory and confirmed that it compiles to binary he posted.

**Comment by MrChromebox** [comment]
ic. what we need is those topology configs for each codec (hopefully not each board) to generate the proper UCM binaries

**Comment by reynhout** [comment]
@doozan I can't quite get this to work on SENTRY/UEFI/max98357. I will try RW_LEGACY tomorrow. What hardware and firmware are you running?

I don't have any cards loaded in `/proc/asound`, so the symlink is not created.

When I copy the `max` firmware file into place manually, I get these messages:

```
[    5.337392] snd_soc_skl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    5.806239] snd_soc_skl 0000:00:1f.3: Direct firmware load for 9d70-INTEL-SCRDMAX-0-tplg.bin failed with error -2
[    5.806243] snd_soc_skl 0000:00:1f.3: tplg fw 9d70-INTEL-SCRDMAX-0-tplg.bin load failed with -2, falling back to dfw_sst.bin
[    5.811499] snd_soc_skl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    5.833233] max98357a MX98357A:00: ASoC: failed to probe component -517
[    5.833248] skl_n88l25_m98357a skl_n88l25_m98357a: ASoC: failed to instantiate card -517
[    6.140251] snd_soc_skl 0000:00:1f.3: Direct firmware load for 9d70-INTEL-SCRDMAX-0-tplg.bin failed with error -2
[    6.140255] snd_soc_skl 0000:00:1f.3: tplg fw 9d70-INTEL-SCRDMAX-0-tplg.bin load failed with -2, falling back to dfw_sst.bin
[    6.140621] snd_soc_skl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    6.140647] general protection fault: 0000 [#1] PREEMPT SMP PTI
[    6.140652] Modules linked in: coretemp(+) kvm_intel lz4 lz4_compress arc4 zram kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc snd_skl_nau88l25_max98357a snd_soc_hdac_hdmi iwlmvm snd_soc_dmic snd_soc_skl_ssp_clk joydev 8250_dw mac80211 nls_iso8859_1 aesni_intel aes_x86_64 crypto_simd glue_helper cryptd snd_soc_skl uvcvideo iwlwifi videobuf2_vmalloc snd_soc_skl_ipc videobuf2_memops videobuf2_v4l2 snd_hda_ext_core btusb snd_soc_sst_dsp snd_soc_max98357a btrtl videobuf2_common btbcm snd_soc_sst_ipc snd_soc_acpi btintel snd_seq_midi snd_hda_core snd_seq_midi_event videodev media cfg80211 bluetooth snd_rawmidi snd_soc_nau8825 ecdh_generic shpchp intel_lpss_pci snd_soc_core intel_lpss snd_compress snd_pcm_dmaengine snd_seq snd_pcm_oss snd_mixer_oss snd_pcm processor_thermal_device
[    6.140704]  intel_soc_dts_iosf snd_seq_device elan_i2c snd_timer snd cros_ec_core mfd_core soundcore int3403_thermal int340x_thermal_zone int3400_thermal acpi_thermal_rel mac_hid sch_fq_codel ip_tables x_tables autofs4 btrfs xor zstd_decompress zstd_compress xxhash raid6_pq dm_mirror dm_region_hash dm_log mmc_block i915 i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sdhci_pci sysimgblt cqhci fb_sys_fops sdhci drm video drm_panel_orientation_quirks
[    6.140738] CPU: 0 PID: 147 Comm: kworker/0:3 Not tainted 4.16.18-galliumos #1
[    6.140740] Hardware name: Google Sentry/Sentry, BIOS MrChromebox 01/04/2019
[    6.140746] Workqueue: events deferred_probe_work_func
[    6.140755] RIP: 0010:skl_tplg_init+0x16f/0x250 [snd_soc_skl]
[    6.140757] RSP: 0000:ffffaca1c08cfc68 EFLAGS: 00010246
[    6.140760] RAX: ffffa038f5e13a98 RBX: ffffffffc0b58f60 RCX: 0000000000000000
[    6.140763] RDX: a6a8d00eda7aa38a RSI: ffffa038f5e0a618 RDI: ffffa038f5e0a6d8
[    6.140765] RBP: ffffa038f363ad58 R08: 0000000000000001 R09: 0000000000000000
[    6.140767] R10: ffffa038f5e133d8 R11: 0000000000000001 R12: ffffa038f4764200
[    6.140769] R13: 0000000000000001 R14: ffffa038f5e0a7d8 R15: ffffa038f4d9eec0
[    6.140772] FS:  0000000000000000(0000) GS:ffffa038fec00000(0000) knlGS:0000000000000000
[    6.140775] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    6.140777] CR2: 00007efc03de8024 CR3: 000000004e00a002 CR4: 00000000002606f0
[    6.140779] Call Trace:
[    6.140788]  skl_platform_soc_probe+0x50/0x230 [snd_soc_skl]
[    6.140800]  soc_probe_component+0x28a/0x3d0 [snd_soc_core]
[    6.140811]  snd_soc_register_card+0x55b/0xe90 [snd_soc_core]
[    6.140822]  ? devm_snd_soc_register_card+0x80/0x80 [snd_soc_core]
[    6.140832]  devm_snd_soc_register_card+0x3c/0x80 [snd_soc_core]
[    6.140837]  platform_drv_probe+0x38/0x90
[    6.140841]  driver_probe_device+0x30b/0x480
[    6.140844]  ? __driver_attach+0xe0/0xe0
[    6.140847]  bus_for_each_drv+0x59/0x90
[    6.140851]  __device_attach+0xb5/0x130
[    6.140855]  bus_probe_device+0x8a/0xa0
[    6.140859]  deferred_probe_work_func+0x42/0x150
[    6.140864]  process_one_work+0x1d4/0x3f0
[    6.140869]  worker_thread+0x2b/0x3d0
[    6.140873]  ? process_one_work+0x3f0/0x3f0
[    6.140876]  kthread+0x113/0x130
[    6.140879]  ? kthread_create_worker_on_cpu+0x50/0x50
[    6.140884]  ret_from_fork+0x35/0x40
[    6.140888] Code: 48 39 d7 48 8d 42 f8 74 6d 31 c9 45 31 c9 eb 14 80 fa 06 48 8b 50 08 41 0f 45 c8 48 39 d7 48 8d 42 f8 74 26 48 8b 10 48 8b 52 30 <0f> b6 92 5a 02 00 00 80 fa 05 75 d9 48 8b 50 08 41 b9 01 00 00 
[    6.140936] RIP: skl_tplg_init+0x16f/0x250 [snd_soc_skl] RSP: ffffaca1c08cfc68
[    6.145312] ---[ end trace 9be8dfa53c63603e ]---
```

Thanks!

**Comment by doozan** [comment]
@reynhout I forgot that I had switched kernels many months ago to fix that exact issue.  Reverting back to the gallium kernel, I get the same error as you.  If I switch to the ukuu v4.16.13 kernel, everything works fine, so it seems like something with the configuration of the gallium kernel.

**Comment by reynhout** [comment]
@doozan Can you share your 4.16.13 kernel config? I don't use ukuu, but the config file should be somewhere in `/boot`.. Ours is at `/boot/config-4.16.18-galliumos`.

**Comment by doozan** [comment]
Here's the config. Ignore the .log extension, github needed that to let me attach

[config-4.16.13-041613-generic.log](https://github.com/GalliumOS/galliumos-skylake/files/3286420/config-4.16.13-041613-generic.log)

**Comment by reynhout** [comment]
@doozan Thanks. I don't see anything obvious in a quick comparison, but will do some more searching. 

Also, can you share the output of `lsmod | grep snd` on your working device? And are you running UEFI or RW_LEGACY firmware? Thanks!

Mine, on non-working SENTRY/UEFI with 4.16.18-galliumos:
```
reynhout@sentry:~$ uname -r
4.16.18-galliumos

reynhout@sentry:~$ dmesg | grep DMI:
[    0.000000] DMI: Google Sentry/Sentry, BIOS MrChromebox-4.9 01/04/2019

reynhout@sentry:~$ lsmod | grep snd
snd_skl_nau88l25_max98357a    24576  0
snd_soc_hdac_hdmi      32768  1 snd_skl_nau88l25_max98357a
snd_soc_dmic           16384  0
snd_soc_skl_ssp_clk    16384  0
snd_soc_skl           114688  1 snd_soc_skl_ssp_clk
snd_soc_skl_ipc        73728  1 snd_soc_skl
snd_hda_ext_core       28672  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_soc_sst_dsp        36864  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_acpi           16384  1 snd_soc_skl
snd_soc_nau8825        53248  1 snd_skl_nau88l25_max98357a
snd_soc_max98357a      16384  0
snd_hda_core           90112  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
snd_pcm_oss            61440  0
snd_soc_core          270336  6 snd_skl_nau88l25_max98357a,snd_soc_hdac_hdmi,snd_soc_max98357a,snd_soc_skl,snd_soc_dmic,snd_soc_nau8825
snd_mixer_oss          28672  1 snd_pcm_oss
snd_compress           24576  1 snd_soc_core
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_seq_midi           16384  0
snd_pcm               135168  9 snd_skl_nau88l25_max98357a,snd_hda_ext_core,snd_soc_hdac_hdmi,snd_pcm_oss,snd_soc_core,snd_soc_skl,snd_hda_core,snd_soc_nau8825,snd_pcm_dmaengine
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            40960  1 snd_seq_midi
snd_seq                81920  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer              36864  2 snd_seq,snd_pcm
snd                    98304  9 snd_seq,snd_seq_device,snd_timer,snd_compress,snd_pcm_oss,snd_soc_core,snd_pcm,snd_rawmidi,snd_mixer_oss
soundcore              16384  1 snd
```

**Comment by doozan** [comment]
I switched to ukuu kernel 4.16.18 to get as close to the gallium kernel as possible, here's their config: 
[config-4.16.18-041618-generic.log](https://github.com/GalliumOS/galliumos-skylake/files/3286813/config-4.16.18-041618-generic.log)

```
jeff@sentry:~$ uname -r
4.16.18-041618-generic

jeff@sentry:~$ dmesg | grep DMI:
[    0.000000] DMI: Google Sentry/Sentry, BIOS MrChromebox 08/02/2018

jeff@sentry:~$ lsmod | grep snd
snd_skl_nau88l25_max98357a    24576  1
snd_soc_hdac_hdmi      28672  1 snd_skl_nau88l25_max98357a
snd_soc_skl_ssp_clk    16384  0
snd_soc_dmic           16384  1
snd_soc_skl            98304  3 snd_soc_skl_ssp_clk
snd_soc_max98357a      16384  1
snd_soc_nau8825        53248  2 snd_skl_nau88l25_max98357a
snd_soc_skl_ipc        65536  1 snd_soc_skl
snd_seq_midi           16384  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_hda_ext_core       24576  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_soc_sst_dsp        32768  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_acpi           16384  1 snd_soc_skl
snd_rawmidi            32768  1 snd_seq_midi
snd_hda_core           81920  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
snd_soc_core          241664  6 snd_skl_nau88l25_max98357a,snd_soc_hdac_hdmi,snd_soc_max98357a,snd_soc_skl,snd_soc_dmic,snd_soc_nau8825
snd_compress           20480  1 snd_soc_core
ac97_bus               16384  1 snd_soc_core
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm                98304  8 snd_skl_nau88l25_max98357a,snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_core,snd_soc_skl,snd_hda_core,snd_soc_nau8825,snd_pcm_dmaengine
snd_seq                65536  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer              32768  2 snd_seq,snd_pcm
snd                    81920  9 snd_seq,snd_seq_device,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi
soundcore              16384  1 snd

```

**Comment by reynhout** [comment]
@doozan Awesome, thank you. I see a couple of possibilities to pursue, though still nothing certain. I'll spin a few kernels to test.

**Comment by bcarnes** [comment]
@doozan From the kernel dmesg output, looks like if you rename your firmware file to 9d70-INTEL-SCRDMAX-0-tplg.bin, you can avoid the card detection and symlinking of dfw_sst.bin, and it will "just work" without requiring a reboot to pick up the firmware load.

> Direct firmware load for 9d70-INTEL-SCRDMAX-0-tplg.bin failed with error -2
> tplg fw 9d70-INTEL-SCRDMAX-0-tplg.bin load failed with -2, falling back to dfw_sst.bin

Similarly, on my Caroline/UEFI, I can rename dfw_sst.bin to 9d70-COREv4-COREBOOT-0-tplg.bin, which is what is tried before it falls back to dfw_sst.bin

This will let various skylake dfw_sst.bin files coexist more gracefully.

**Comment by bcarnes** [comment]
@doozan Changed the caroline side: see #3 
Do the equivalent for Sentry, and you can ditch the card detection and symlinking.

**Comment by doozan** [comment]
@bcarnes Great find, it's much better this way! I've removed the symlinking and renamed the file to 9d70-INTEL-SCRDMAX-0-tplg.bin

**Comment by reynhout** [comment]
@doozan Still spinning kernels here. Neither of my leads panned out, nor have a few other guesses. I might resort to bisecting tomorrow.

@bcarnes and @MrChromebox Re: firmware file renaming, any chance the new names are over- (or under-) specified? Might the `9d70-INTEL-SCRDMAX-0-tplg.bin` file work for, but fail to match on, another model or firmware?

The `9d70-COREv4-COREBOOT-0-tplg.bin` name looks tricky too... @MrChromebox does CHELL look for that same filename?

**Comment by MrChromebox** [comment]
> The 9d70-COREv4-COREBOOT-0-tplg.bin name looks tricky too... @MrChromebox does CHELL look for that same filename?

yes, it's per codec I believe - those two names should be safe to cover all SKL CrOS devices

**Comment by reynhout** [comment]
@doozan OK, found the kernel issue. I was overlooking the new PINCTRL parm for Sunrise Point. Thank you for your help!

**Comment by reynhout** [comment]
@MrChromebox @bcarnes @doozan 

On my CAROLINE, the kernel looks for firmware file `9d70-CORE-COREBOOT-0-tplg.bin` (not `COREv4`). I will add another symlink to the `adi` file. I guess we'll need to watch for other variations.

**Comment by bcarnes** [comment]
@reynhout
> OK, found the kernel issue. I was overlooking the new PINCTRL parm for Sunrise Point. 

Did your kernel pinctrl enablement stuff fix the SDHCI card present pins too?

w/ the latest kernel and -skylake pkgs, I find the SDHCI w/ empty slot problems have gone away on Caroline.

Card empty/insert/eject/re-insert all seem to work well.

Nuked the /etc/modprobe.d/sdhci.conf to get rid of the "quirks" param, rebuilt the initramfs, and things still look good.

Consider testing that yourself on your larger number of devices, and declaring the SDHCI problem fixed by this kernel update as well.

**Comment by reynhout** [comment]
@bcarnes I thought I saw some improvement there as well, but the results have been inconsistent over time on CAROLINE. Just rebooted to check, and I am getting the errors presently. Shutdown and suspend have been consistently good for several kernel builds on CAROLINE...but not on SENTRY. I also tried removing the modprobe config, which didn't seem to have any effect, good or ill.

So, needs more research, but the hope is still that we will be able to fully resolve this issue in kernel config. It's next on the list, but not a blocker for 3.0final.

**Comment by bcarnes** [comment]
> I also tried removing the modprobe config, which didn't seem to have any effect, good or ill.

@reynhout Did you "update-initramfs -u -k all" after removing the sdhci.conf modprobe?

See https://github.com/GalliumOS/galliumos-distro/issues/510 for detailed repro of bug and fix from a fresh install.

**Comment by reynhout** [comment]
@bcarnes Thank you, that explains it. I must have overlapped the modprobe file edit with a kernel update and postinstall initramfs update at least once while testing, which is why I saw a temporary improvement.

I didn't expect that a modprobe config change would require rebuilding initramfs. I guess the issue is that mmc/sdhci are required before the filesystem is available, which...makes sense!

Thanks again, very happy to have that resolved.

**Pull request merged**
